-- Defaults do conteúdo editável — mesmo texto que já estava hardcoded no index.html,
-- então nada muda visualmente até o usuário editar algo pela aba "Conteúdo" do admin.
INSERT INTO eventos (id, slug, nome, criado_em) VALUES (1, 'casamento', 'Casamento', datetime('now'));

INSERT INTO conteudo (evento_id, chave, valor) VALUES
(1, 'hero.eyebrow', 'Nosso casamento'),
(1, 'hero.noiva', 'Noiva'),
(1, 'hero.noivo', 'Noivo'),
(1, 'hero.data_iso', '2027-06-12T15:00:00-03:00'),
(1, 'hero.data_display', '12 de junho de 2027'),
(1, 'hero.horario_display', 'às 15h00'),
(1, 'hero.prazo_iso', '2027-05-01T23:59:59-03:00'),
(1, 'hero.prazo_display', '01 de maio'),
(1, 'hero.cta_label', 'Confirmar Presença →'),
(1, 'hero.foto_url', ''),

(1, 'secao.countdown.ativa', '1'),
(1, 'countdown.eyebrow', 'Para o grande dia'),
(1, 'countdown.titulo', 'Faltam apenas'),

(1, 'secao.presente_teaser.ativa', '1'),
(1, 'presente_teaser.titulo', 'Um mimo pra gente?'),
(1, 'presente_teaser.texto', 'Se quiser fazer parte desse momento, escolha um presente especial com muito carinho pra gente.'),
(1, 'presente_teaser.cta_label', 'Ver lista de presentes →'),

(1, 'secao.timeline.ativa', '1'),
(1, 'timeline.eyebrow', 'Nossa história ❤️'),
(1, 'timeline.titulo', 'Duas vidas, um caminho'),
(1, 'timeline.node1.ano', '2000 👶'),
(1, 'timeline.node1.titulo', 'Nascimento da Noiva'),
(1, 'timeline.node1.texto', 'A noiva chegou ao mundo, sem imaginar as surpresas que a vida ainda guardava pra ela.'),
(1, 'timeline.node2.ano', '2001 👶'),
(1, 'timeline.node2.titulo', 'Nascimento do Noivo'),
(1, 'timeline.node2.texto', 'O noivo chegou ao mundo, sem imaginar que um dia encontraria o amor da sua vida.'),
(1, 'timeline.node3.ano', 'Ao longo dos anos 🤝'),
(1, 'timeline.node3.titulo', 'Nossas famílias se conheceram'),
(1, 'timeline.node3.texto', 'Nossas famílias se conheceram e construíram uma bonita amizade, sem imaginar o que o futuro reservava pra gente.'),
(1, 'timeline.node4.ano', '2018 ✈️'),
(1, 'timeline.node4.titulo', 'O dia que nossos olhos se encontraram'),
(1, 'timeline.node4.texto', 'Nos vimos pela primeira vez em um encontro casual entre amigos. Naquele momento, éramos apenas dois desconhecidos, sem imaginar que ali começava a nossa história.'),
(1, 'timeline.node5.ano', '2021 ✨'),
(1, 'timeline.node5.titulo', 'O dia que nasceu a nossa amizade'),
(1, 'timeline.node5.texto', 'Nos reencontramos de um jeito especial, e foi ali que nasceu uma amizade sincera que, com o tempo, se transformaria em algo ainda mais bonito.'),
(1, 'timeline.node6.ano', '2022 💕'),
(1, 'timeline.node6.titulo', 'O início do nosso namoro'),
(1, 'timeline.node6.texto', 'Com a bênção de nossas famílias, iniciamos oficialmente o nosso namoro, dando início a uma caminhada de amor, companheirismo e crescimento juntos.'),
(1, 'timeline.node7.ano', '2024 💍'),
(1, 'timeline.node7.titulo', 'Os preparativos para o casamento'),
(1, 'timeline.node7.texto', 'Depois de muita conversa e certeza um do outro, decidimos dar o próximo passo e iniciar os preparativos para o nosso casamento.'),
(1, 'timeline.node8.ano', '2025 💍❤️'),
(1, 'timeline.node8.titulo', 'O pedido de casamento'),
(1, 'timeline.node8.texto', 'Veio o tão esperado pedido de casamento. Com muita alegria e emoção, dissemos "sim" ao futuro que queremos construir juntos.'),
(1, 'timeline.node9.ano', '2026 🤵👰'),
(1, 'timeline.node9.titulo', 'O grande dia'),
(1, 'timeline.node9.texto', 'Chegou o grande dia! Cercados de quem amamos, celebraremos o início de uma nova história, que pretendemos escrever juntos por toda a vida.'),

(1, 'secao.mapa.ativa', '1'),
(1, 'mapa.eyebrow', 'Localização'),
(1, 'mapa.titulo', 'Local da realização de nossos sonhos'),
(1, 'mapa.local_nome', 'Copacabana Palace'),
(1, 'mapa.local_endereco', 'Av. Atlântica, 1702, Copacabana, Rio de Janeiro'),
(1, 'mapa.cta_label', 'Como chegar ↗'),

(1, 'secao.galeria.ativa', '1'),
(1, 'galeria.eyebrow', 'Galeria'),
(1, 'galeria.titulo', 'Momentos para sempre'),
(1, 'galeria.foto1_url', ''),
(1, 'galeria.foto2_url', ''),
(1, 'galeria.foto3_url', ''),
(1, 'galeria.foto4_url', ''),
(1, 'galeria.foto5_url', ''),
(1, 'galeria.foto6_url', ''),

(1, 'rsvp.eyebrow', 'Confirme sua presença'),
(1, 'rsvp.titulo', 'Estamos preparando cada detalhe'),
(1, 'rsvp.texto', 'Com muito carinho, para celebrar esse dia especial com você. Por favor, confirme a presença de cada pessoa do seu grupo até a data indicada. 🤍'),
(1, 'rsvp.sem_codigo_texto', 'Não encontramos um código de convite nesta página. Peça o link personalizado de confirmação a quem te convidou.'),
(1, 'rsvp.sucesso_texto', 'Presença confirmada! Obrigado 💛'),
(1, 'rsvp.cta_label', 'Confirmar Presença →'),

(1, 'secao.presentes.ativa', '1'),
(1, 'presentes.eyebrow', 'Lista de presentes'),
(1, 'presentes.titulo', 'Seja protagonista da nossa história'),
(1, 'presentes.texto', 'Escolha o presente que você gostaria de nos dar e deixe uma mensagem carinhosa — cada gesto vai morar com a gente para sempre.'),
(1, 'presentes.cta_label', 'Escolher Presente →'),
(1, 'presentes.cta_url', '#'),

(1, 'footer.texto', 'Feito com amor'),
(1, 'sticky.titulo', 'Confirme sua presença'),
(1, 'sticky.cta_label', 'Confirmar →'),

(1, 'config.meta_convidados', '150'),
(1, 'config.mensagem_template', 'Oi {nome}! Poderia confirmar sua presença no nosso casamento através deste link? {link} 💛'),

(1, 'aparencia.cor_primaria', '#0B2545'),
(1, 'aparencia.cor_secundaria', '#2F5D9A'),
(1, 'aparencia.cor_destaque', '#C9A227'),
(1, 'aparencia.cor_fundo', '#EAF1FB'),
(1, 'aparencia.cor_texto', '#14213D'),
(1, 'aparencia.fontes', 'classico'),

(1, 'countdown.layout', '1'),
(1, 'sticky.subtexto_template', 'até {prazo}'),
(1, 'mapa.mostrar_botao_copiar', '0'),

(1, 'config.modo_save_the_date', '0'),
(1, 'savethedate.titulo', 'Guarde a data!'),
(1, 'savethedate.texto', 'Em breve mais detalhes do nosso grande dia.'),

(1, 'secao.recados.ativa', '1'),
(1, 'recados.eyebrow', 'Recados'),
(1, 'recados.titulo', 'Deixe seu recado'),
(1, 'recados.texto', 'Escreva uma mensagem carinhosa pra gente guardar para sempre.'),

(1, 'config.mostrar_menu', '0'),

(1, 'secao.padrinhos.ativa', '0'),
(1, 'padrinhos.eyebrow', 'Com carinho'),
(1, 'padrinhos.titulo', 'Padrinhos e Madrinhas'),
(1, 'padrinhos.pessoas', '[]'),

(1, 'secao.madrinhas_pais.ativa', '0'),
(1, 'madrinhas_pais.eyebrow', 'Com carinho'),
(1, 'madrinhas_pais.titulo', 'Pais e Daminhas'),
(1, 'madrinhas_pais.pessoas', '[]'),

(1, 'presentes.chave_pix', ''),
(1, 'presentes.itens', '[]'),

(1, 'layout.ordem', '[]');
