-- Defaults do conteúdo editável — mesmo texto que já estava hardcoded no index.html,
-- então nada muda visualmente até o usuário editar algo pela aba "Conteúdo" do admin.
INSERT INTO conteudo (chave, valor) VALUES
('hero.eyebrow', 'Nosso casamento'),
('hero.noiva', 'Noiva'),
('hero.noivo', 'Noivo'),
('hero.data_iso', '2027-06-12T15:00:00-03:00'),
('hero.data_display', '12 de junho de 2027'),
('hero.horario_display', 'às 15h00'),
('hero.prazo_iso', '2027-05-01T23:59:59-03:00'),
('hero.prazo_display', '01 de maio'),
('hero.cta_label', 'Confirmar Presença →'),
('hero.foto_url', ''),

('secao.countdown.ativa', '1'),
('countdown.eyebrow', 'Para o grande dia'),
('countdown.titulo', 'Faltam apenas'),

('secao.presente_teaser.ativa', '1'),
('presente_teaser.titulo', 'Um mimo pra gente?'),
('presente_teaser.texto', 'Se quiser fazer parte desse momento, escolha um presente especial com muito carinho pra gente.'),
('presente_teaser.cta_label', 'Ver lista de presentes →'),

('secao.timeline.ativa', '1'),
('timeline.eyebrow', 'Nossa história ❤️'),
('timeline.titulo', 'Duas vidas, um caminho'),
('timeline.node1.ano', '2000 👶'),
('timeline.node1.titulo', 'Nascimento da Noiva'),
('timeline.node1.texto', 'A noiva chegou ao mundo, sem imaginar as surpresas que a vida ainda guardava pra ela.'),
('timeline.node2.ano', '2001 👶'),
('timeline.node2.titulo', 'Nascimento do Noivo'),
('timeline.node2.texto', 'O noivo chegou ao mundo, sem imaginar que um dia encontraria o amor da sua vida.'),
('timeline.node3.ano', 'Ao longo dos anos 🤝'),
('timeline.node3.titulo', 'Nossas famílias se conheceram'),
('timeline.node3.texto', 'Nossas famílias se conheceram e construíram uma bonita amizade, sem imaginar o que o futuro reservava pra gente.'),
('timeline.node4.ano', '2018 ✈️'),
('timeline.node4.titulo', 'O dia que nossos olhos se encontraram'),
('timeline.node4.texto', 'Nos vimos pela primeira vez em um encontro casual entre amigos. Naquele momento, éramos apenas dois desconhecidos, sem imaginar que ali começava a nossa história.'),
('timeline.node5.ano', '2021 ✨'),
('timeline.node5.titulo', 'O dia que nasceu a nossa amizade'),
('timeline.node5.texto', 'Nos reencontramos de um jeito especial, e foi ali que nasceu uma amizade sincera que, com o tempo, se transformaria em algo ainda mais bonito.'),
('timeline.node6.ano', '2022 💕'),
('timeline.node6.titulo', 'O início do nosso namoro'),
('timeline.node6.texto', 'Com a bênção de nossas famílias, iniciamos oficialmente o nosso namoro, dando início a uma caminhada de amor, companheirismo e crescimento juntos.'),
('timeline.node7.ano', '2024 💍'),
('timeline.node7.titulo', 'Os preparativos para o casamento'),
('timeline.node7.texto', 'Depois de muita conversa e certeza um do outro, decidimos dar o próximo passo e iniciar os preparativos para o nosso casamento.'),
('timeline.node8.ano', '2025 💍❤️'),
('timeline.node8.titulo', 'O pedido de casamento'),
('timeline.node8.texto', 'Veio o tão esperado pedido de casamento. Com muita alegria e emoção, dissemos "sim" ao futuro que queremos construir juntos.'),
('timeline.node9.ano', '2026 🤵👰'),
('timeline.node9.titulo', 'O grande dia'),
('timeline.node9.texto', 'Chegou o grande dia! Cercados de quem amamos, celebraremos o início de uma nova história, que pretendemos escrever juntos por toda a vida.'),

('secao.mapa.ativa', '1'),
('mapa.eyebrow', 'Localização'),
('mapa.titulo', 'Local da realização de nossos sonhos'),
('mapa.local_nome', 'Copacabana Palace'),
('mapa.local_endereco', 'Av. Atlântica, 1702, Copacabana, Rio de Janeiro'),
('mapa.cta_label', 'Como chegar ↗'),

('secao.galeria.ativa', '1'),
('galeria.eyebrow', 'Galeria'),
('galeria.titulo', 'Momentos para sempre'),
('galeria.foto1_url', ''),
('galeria.foto2_url', ''),
('galeria.foto3_url', ''),
('galeria.foto4_url', ''),
('galeria.foto5_url', ''),
('galeria.foto6_url', ''),

('rsvp.eyebrow', 'Confirme sua presença'),
('rsvp.titulo', 'Estamos preparando cada detalhe'),
('rsvp.texto', 'Com muito carinho, para celebrar esse dia especial com você. Por favor, confirme a presença de cada pessoa do seu grupo até a data indicada. 🤍'),
('rsvp.sem_codigo_texto', 'Não encontramos um código de convite nesta página. Peça o link personalizado de confirmação a quem te convidou.'),
('rsvp.sucesso_texto', 'Presença confirmada! Obrigado 💛'),
('rsvp.cta_label', 'Confirmar Presença →'),

('secao.presentes.ativa', '1'),
('presentes.eyebrow', 'Lista de presentes'),
('presentes.titulo', 'Seja protagonista da nossa história'),
('presentes.texto', 'Escolha o presente que você gostaria de nos dar e deixe uma mensagem carinhosa — cada gesto vai morar com a gente para sempre.'),
('presentes.cta_label', 'Escolher Presente →'),
('presentes.cta_url', '#'),

('footer.texto', 'Feito com amor'),
('sticky.titulo', 'Confirme sua presença'),
('sticky.cta_label', 'Confirmar →'),

('config.meta_convidados', '150'),
('config.mensagem_template', 'Oi {nome}! Poderia confirmar sua presença no nosso casamento através deste link? {link} 💛');
